// Vue/day6/toutiao4/src/components/search/search.vue
<template>
  <div
    v-bind:abc="title"
    :class="['weui-search-bar',{
    'weui-search-bar_focusing': isFocus
}]"
    id="searchBar"
  >
    <form class="weui-search-bar__form">
      <div class="weui-search-bar__box">
        <i class="weui-icon-search"></i>
        <input
          ref="input"
          v-model="searchText"
          type="search"
          class="weui-search-bar__input"
          id="searchInput"
          placeholder="搜索"
          required
        />
        <a @click="clear" href="javascript:" class="weui-icon-clear" id="searchClear"></a>
      </div>
      <label
        @click="toggleFocus"
        class="weui-search-bar__label"
        id="searchText"
        style="transform-origin: 0px 0px; opacity: 1; transform: scale(1, 1);"
      >
        <i class="weui-icon-search"></i>
        <span>{{title}}</span>
      </label>
    </form>
    <a
      v-on:click="toggleFocus"
      href="javascript:"
      class="weui-search-bar__cancel-btn"
      id="searchCancel"
    >{{cancel}}</a>
  </div>
</template>
<script>
import txt from './search.txt'
import observer from '../../tools/observer'
export default {
    data() {
        return {
            // 表示搜索框的两个状态，一个是聚焦后的，一个是非聚焦
            isFocus: false,
            // 搜索框的值
            searchText: '',
            title: txt,
            cancel: '取消',
        }
    },
    // 注册事件
    methods: {
        toggleFocus() {
            this.isFocus = !this.isFocus
            // 聚焦
            this.$refs.input.focus()
            // search.isFocus = false
            console.log('点击了取消')
        },
        // 清空输入框
        clear() {
            this.searchText = ''
        }
    },
    watch: {
        // 监听搜索框
        searchText() {
            // 使用观察者模式
            observer.emit('setSeatchText', this.searchText)
        }
    }
}
</script>

// React/day2/react-project/src/components/Search/index.jsx
import React from 'react';

export default class Search extends React.Component {
  constructor(props) {
    console.log('---------beforeCreated-------------')
    super(props)
    this.state = {
      searchText: '',
      isFocus: false
    }
    console.log('---------Created-------------')
  }
  componentWillMount() {
    console.log('---------componentWillMount-------------')
  }
  //   --------- 这里会有一次render--------------
  componentDidMount() {
    console.log('---------componentDidMount-------------')
  }
  componentWillUpdate() {
    console.log('---------componentWillUpdate-------------')
  }
  //   --------- 如果有数据更新，这里会有一次render--------------
  componentDidUpdate() {
    console.log('---------componentDidUpdate-------------')
  }
  componentWillUnmount() {
    console.log('---------componentWillUnmount-------------')
  }
  toggle(){
    this.setState({
      isFocus: !this.state.isFocus
    })
  }
  getInputValue(e){
    this.setState({
      searchText: e.target.value
    })
  }
  clear(){
    this.setState({
      searchText: ''
    })
  }
  render() {
    console.log('--------------render-----------')
    return (
      <div className={
        this.state.isFocus ? 'weui-search-bar weui-search-bar_focusing' : 'weui-search-bar'
      } id="searchBar">
        <form className="weui-search-bar__form">
          <div className="weui-search-bar__box">
            <i className="weui-icon-search"></i>
            <input value={this.state.searchText} onChange={this.getInputValue.bind(this)} type="search" className="weui-search-bar__input" id="searchInput" placeholder="搜索" required="" />
            <a onClick={this.clear.bind(this)} className="weui-icon-clear" id="searchClear"></a>
          </div>
          <label onClick={this.toggle.bind(this)} className="weui-search-bar__label" id="searchText">
            <i className="weui-icon-search"></i>
            <span>搜索</span>
          </label>
        </form>
        <a onClick={this.toggle.bind(this)} className="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
      </div>
    )
  }
}
