// React/day2/react-project/src/components/Panel/index.jsx
import React from 'react';
import axios from 'axios';

export default class Panel extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      news: [],
      page: 1,
      isLoading: false
    }
  }
  UNSAFE_componentWillMount() {
    //挂载前
    this.loadMore()
  }
  async loadMore() {
    this.setState({
      isLoading: true,
    })
    let data = await axios.get('https://cnodejs.org/api/v1/topics', {
      params: {
        page: this.state.page,
        tab: 'ask',
        limit: 10,
        mdrender: true
      }
    })
    console.log(data.data.data)
    this.setState({
      isLoading: false,
      page: ++this.state.page,
      news: [...this.state.news, ...data.data.data]
    })
  }
  render() {
    return (
      <div className="weui-panel weui-panel_access">
        <div className="weui-panel__bd">
          {
            this.state.news.map((item, index) => {
              return (
                <a key={index} className="weui-media-box weui-media-box_appmsg">
                  <div className="weui-media-box__hd">
                    <img className="weui-media-box__thumb" src={item.author.avatar_url} alt="" />
                  </div>
                  <div className="weui-media-box__bd">
                    <h4 className="weui-media-box__title">{item.title}</h4>
                    <p className="weui-media-box__desc">{item.author.loginname}</p>
                  </div>
                </a>
              )
            })
          }
        </div>
        <div onClick={this.loadMore.bind(this)} className="weui-panel__ft">
          <a className="weui-cell weui-cell_access weui-cell_link">
            <div className="weui-cell__bd">查看更多</div>
            <span className="weui-cell__ft"></span>
          </a>
        </div>
      </div>
    )
  }
}

// Vue/day7/toutiao5/src/components/panel.vue
<template>
  <div class="weui-panel weui-panel_access">
    <div class="weui-panel__bd">
      <router-link
        v-for="(item,index) in newsComputed"
        :key="index"
        href="javascript:void(0);"
        class="weui-media-box weui-media-box_appmsg"
        :to="{
          name: 'detail',
          params:{
            id: index
          }
        }"
      >
        <div class="weui-media-box__hd">
          <img class="weui-media-box__thumb" :src="item.author.avatar_url" alt />
        </div>
        <div class="weui-media-box__bd">
          <h4 class="weui-media-box__title" v-text="item.title"></h4>
          <p class="weui-media-box__desc">{{item.author.loginname|captian}}</p>
        </div>
      </router-link>
    </div>
    <div @click="getNews" class="weui-panel__ft">
      <a href="javascript:void(0);" class="weui-cell weui-cell_access weui-cell_link">
        <div class="weui-cell__bd">查看更多</div>
        <span class="weui-cell__ft"></span>
      </a>
    </div>
  </div>
</template>
<script>
import axios from "axios";
import observer from "../tools/observer.js";
export default {
  props: {
    tab: String
  },
  data() {
    return {
      // 新闻数据
      news: [],
      page: 1,
      searchText: ""
    };
  },
  methods: {
    getNews() {
      let _self = this;
      axios
        .get("https://cnodejs.org/api/v1/topics", {
          params: {
            page: this.page++, //Number 页数
            tab: this.tab, // String 主题分类。目前有 ask share job good
            limit: 10, // Number 每一页的主题数量
            mdrender: false // String 当为 false 时
          }
        })
        .then(data => {
          // 注意this的指向问题，如果是箭头函数，那这里就直接指向外部
          // 相当concat的方法，合并数组
          _self.news = [..._self.news, ...data.data.data];
          console.log(data);
        });
    }
  },
  computed: {
    newsComputed() {
      console.log(this.searchText);
      // 有搜索值的时候就执行过滤逻辑，否则原封不动返回原数组
      if (this.searchText) {
        return this.news.filter(item => {
          if (item.title.indexOf(this.searchText) != -1) {
            return item;
          }
        });
      } else {
        return this.news;
      }
    }
  },
  mounted() {
    console.log(observer);
    observer.on("setSeatchText", searchText => {
      this.searchText = searchText;
    });
    console.log(this);
    this.getNews();
  },
  filters: {
    // 首字母的大写
    captian(value) {
      // value是放进来要处理的数据
      return value.charAt(0).toUpperCase() + value.slice(1);
    }
  }
};
</script>
